var FeedbackItem = DS.Model.extend({
    text: DS.attr('string'),
    feedback: DS.belongsTo('feedback', { async: true }),
});


FeedbackItem.reopenClass({
    FIXTURES: [{
        id: 1,
        feedback: 1,
        text: ''
    }, {
        id: 2,
        feedback: 1,
        text: ''
    }, {
        id: 3,
        feedback: 1,
        text: ''
    }, {
        id: 4,
        feedback: 1,
        text: ''
    }, {
        id: 5,
        feedback: 1,
        text: ''
    }, {
        id: 6,
        feedback: 1,
        text: ''
    }, {
        id: 7,
        feedback: 1,
        text: ''
    }, {
        id: 8,
        feedback: 2,
        text: ''
    }, {
        id: 9,
        feedback: 2,
        text: ''
    }, {
        id: 10,
        feedback: 2,
        text: ''
    }, {
        id: 11,
        feedback: 2,
        text: ''
    }, {
        id: 12,
        feedback: 2,
        text: ''
    }, {
        id: 13,
        feedback: 2,
        text: ''
    }, {
        id: 14,
        feedback: 2,
        text: ''
    }, {
        id: 15,
        feedback: 2,
        text: ''
    }, {
        id: 16,
        feedback: 3,
        text: ''
    }, {
        id: 17,
        feedback: 3,
        text: ''
    }, {
        id: 18,
        feedback: 3,
        text: ''
    }, {
        id: 19,
        feedback: 3,
        text: ''
    }, {
        id: 20,
        feedback: 3,
        text: ''
    }, {
        id: 21,
        feedback: 3,
        text: ''
    }, {
        id: 22,
        feedback: 3,
        text: ''
    }, {
        id: 23,
        feedback: 3,
        text: ''
    }, {
        id: 24,
        feedback: 4,
        text: ''
    }, {
        id: 25,
        feedback: 4,
        text: ''
    }, {
        id: 26,
        feedback: 4,
        text: ''
    }, {
        id: 27,
        feedback: 4,
        text: ''
    }, {
        id: 28,
        feedback: 4,
        text: ''
    }, {
        id: 29,
        feedback: 4,
        text: ''
    }, {
        id: 30,
        feedback: 4,
        text: ''
    }, {
        id: 31,
        feedback: 4,
        text: ''
    }, {
        id: 32,
        feedback: 5,
        text: ''
    }, {
        id: 33,
        feedback: 5,
        text: ''
    }, {
        id: 34,
        feedback: 5,
        text: ''
    }, {
        id: 35,
        feedback: 5,
        text: ''
    }, {
        id: 36,
        feedback: 5,
        text: ''
    }, {
        id: 37,
        feedback: 5,
        text: ''
    }, {
        id: 38,
        feedback: 5,
        text: ''
    }, {
        id: 39,
        feedback: 5,
        text: ''
    }, {
        id: 40,
        feedback: 6,
        text: ''
    }, {
        id: 41,
        feedback: 6,
        text: ''
    }, {
        id: 42,
        feedback: 6,
        text: ''
    }, {
        id: 43,
        feedback: 6,
        text: ''
    }, {
        id: 44,
        feedback: 6,
        text: ''
    }, {
        id: 45,
        feedback: 6,
        text: ''
    }, {
        id: 46,
        feedback: 6,
        text: ''
    }, {
        id: 47,
        feedback: 6,
        text: ''
    }, {
        id: 48,
        feedback: 7,
        text: ''
    }, {
        id: 49,
        feedback: 7,
        text: ''
    }, {
        id: 50,
        feedback: 7,
        text: ''
    }, {
        id: 51,
        feedback: 7,
        text: ''
    }, {
        id: 52,
        feedback: 7,
        text: ''
    }, {
        id: 53,
        feedback: 7,
        text: ''
    }, {
        id: 54,
        feedback: 7,
        text: ''
    }, {
        id: 55,
        feedback: 7,
        text: ''
    }, {
        id: 56,
        feedback: 8,
        text: ''
    }, {
        id: 57,
        feedback: 8,
        text: ''
    }, {
        id: 58,
        feedback: 8,
        text: ''
    }, {
        id: 59,
        feedback: 8,
        text: ''
    }, {
        id: 60,
        feedback: 8,
        text: ''
    }, {
        id: 61,
        feedback: 8,
        text: ''
    }, {
        id: 62,
        feedback: 8,
        text: ''
    }, {
        id: 63,
        feedback: 8,
        text: ''
    }, ]

});

export default FeedbackItem;
